# Generated by Django 2.0.2 on 2018-02-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=30)),
                ('target_type', models.CharField(max_length=30)),
                ('target_action', models.CharField(max_length=30)),
            ],
        ),
    ]
