# Generated by Django 2.0.2 on 2018-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_action',
            field=models.CharField(choices=[('F', 'Follow'), ('L', 'Like'), ('C', 'Comment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('T', 'Tag'), ('P', 'Page'), ('L', 'Place')], max_length=1),
        ),
    ]
