# Generated by Django 2.0.2 on 2018-03-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_follows',
            field=models.CharField(choices=[('F', 'Likers'), ('L', 'Followers')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='target_action',
            field=models.CharField(max_length=3),
        ),
    ]
