# Generated by Django 2.0.2 on 2018-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180309_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='conf_path',
        ),
        migrations.AddField(
            model_name='bot',
            name='comment_per_day',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bot',
            name='comments',
            field=models.TextField(default='salam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='follow_per_day',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bot',
            name='like_per_day',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='bot',
            name='password',
            field=models.CharField(default='morteza76', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='second_password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='second_username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='unfollow_per_day',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(default='amir___ali98', max_length=30),
            preserve_default=False,
        ),
    ]
