# Generated by Django 2.0.2 on 2018-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180309_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
