# Generated by Django 2.0.2 on 2018-03-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180310_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(default='not_set', max_length=30),
            preserve_default=False,
        ),
    ]
