# Generated by Django 2.0.2 on 2018-03-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='second_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
