# Generated by Django 2.0.2 on 2018-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180311_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='second_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='second_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
