# Generated by Django 2.0.2 on 2018-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180311_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
