# Generated by Django 2.0.2 on 2018-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_target_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='follow_back_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='follower_num',
            field=models.IntegerField(default=0),
        ),
    ]
